server:
  port: 8521
spring:
  application:
    name: consumer
  cloud:
    consul:
      host: 47.103.115.230
      port: 8500
      discovery:
        register: true    #设置不需要注册到 consul 中
        health-check-path: /actuator/health   #定义 consul 健康检查路径
        health-check-interval: 10s # consul 健康检查频率
        instance-id: ${spring.application.name}:${server.port} # 配置注册到consul 服务的id
        enabled: true #启用 consul 服务发现
        service-name: ${spring.application.name} #设置 注册到 consul 的服务名称
        ip-address: 127.0.0.1 # 访问服务时使用的 ip地址 （还必须设置preferIpAddress才能使用）
        prefer-ip-address: true